### PR TITLE
Create SwapRegions.py

### LINKED ISSUE #36: Setup API Call/Write Lambda Handler for Swap Region Function

### PR DESCRIPTION
**Pull request by RauschJames**
Creates Swap Region ,updated to use STS Authentication method as well.

### CODE REVIEW

**Comment by arotty** [comment]
function should assume the role of an aws user so that it can change the region for any given user's bucket. Check listBucketData.py

**Comment by RauschJames** [comment]
thanks so much Alex for the feedback, ill take the AR to update all the outstanding functions as well for the team!

**Comment by RauschJames** [comment]
Updated + updated outstanding functions

**Comment by arotty** [comment]
Hi, I noticed a few more small errors upon further review. I will post the comments now

Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, Jan 25, 2024 at 8:18 AM, ***@***.***> wrote:   


Updated + updated outstanding functions

**Comment by arotty** [comment]
Whenever you are creating a new client after assuming a role you need to set your session configurations to the region where the client bucket is located like so "config=boto3.session.Config(signature_version='s3v4', region_name=s3_region)" if you are going to want to access the bucket

Also, this line "boto3.setup_default_session(region_name=lambda_region)" (the region is where your lambda function is located) was necessary for me as when calling my API the "get_bucket_location" function was overriding my default session region which was not allowing my lambda function to run.

**Comment by RauschJames** [comment]
Alex, thank you for the knowledgeable feedback.
I will look to make these changes hopefully prior to our meeting today :)

**Comment by arotty** [comment]
Yeah no problem!

Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, Jan 25, 2024 at 8:47 AM, ***@***.***> wrote:   


Alex, thank you for the knowledgeable feedback.
I will look to make these changes hopefully prior to our meeting today :)

**Comment by RauschJames** [comment]
Closing, 
Addressing errors
1: region_name=s3_region was set , added hardcoding for s3v4 as proposed
2: added in case as suggested.

**Pull request merged**
